
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class Author extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    Connection con1,con2,con3;
    PreparedStatement select,insert,add,delete,update,tbl;
    ResultSet rs;
    public Author() {
        Connect();
        initComponents();
        table_author();
    }
    
public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUP.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
            } catch (SQLException ex) {
                System.out.print(ex);
            }
    }
private void table_author()
    {
        try{
            tbl = con1.prepareStatement("select * from author_table");
            rs = tbl.executeQuery();
            
            javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String phone = rs.getString("phone");
                String address = rs.getString("address");
                
                String row[] = {id,name,phone,address};
                df.addRow(row);
            }
        }catch(SQLException ex)
        {
            System.out.print(ex);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtfldNameAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JToggleButton();
        jtxtfldPhoneAuthor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonDeleteAuthor = new javax.swing.JToggleButton();
        jButtonAddAuthor = new javax.swing.JToggleButton();
        jButtonUpdateAuthor = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtxtfldNameAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 300, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 40));

        back.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 190, 40));
        getContentPane().add(jtxtfldPhoneAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 300, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 40));
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 300, 150));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 40));

        jButtonDeleteAuthor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDeleteAuthor.setText("Delete");
        jButtonDeleteAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 110, 40));

        jButtonAddAuthor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddAuthor.setText("Add");
        jButtonAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 110, 40));

        jButtonUpdateAuthor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonUpdateAuthor.setText("Edit");
        jButtonUpdateAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 0, 530, 650));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\Smaller\\Author.jpg")); // NOI18N
        jToggleButton1.setText("Author");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Library.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        LibrarianMenu back = new LibrarianMenu();
        back.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jButtonDeleteAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAuthorActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(df.getValueAt(selectIndex,0).toString());
        
        String name,phn,adrs;
        name = jtxtfldNameAuthor.getText();
        phn = jtxtfldPhoneAuthor.getText();
        adrs = jTextArea1.getText();
        
        try{
            delete = con1.prepareStatement("delete from author_table where id=?");
            delete.setInt(1, id);
            int k = delete.executeUpdate();
                
            if(k == 1)
              {
                JOptionPane.showMessageDialog(this,"Data Deleted!");
                  
                jtxtfldNameAuthor.setText("");
                jtxtfldPhoneAuthor.setText("");
                jTextArea1.setText("");
                jtxtfldNameAuthor.requestFocus();
                
                table_author();
                jButtonAddAuthor.setEnabled(true);
              }
              else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonDeleteAuthorActionPerformed

    private void jButtonAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAuthorActionPerformed
        // TODO add your handling code here:
        String name,phn,adrs;
        name = jtxtfldNameAuthor.getText();
        phn = jtxtfldPhoneAuthor.getText();
        adrs = jTextArea1.getText();
        
        
        try{
            if(name.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please fill up the text field to add new author!");
            }
            else
            {
                insert = con1.prepareStatement("insert into author_table(name,phone,address) values(?,?,?)");
                insert.setString(1, name);
                insert.setString(2, phn);
                insert.setString(3, adrs);
                int k = insert.executeUpdate();
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data inserted!");
                    
                    jtxtfldNameAuthor.setText("");
                    jtxtfldPhoneAuthor.setText("");
                    jTextArea1.setText("");
                    jtxtfldNameAuthor.requestFocus();
                   
                    table_author();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonAddAuthorActionPerformed

    private void jButtonUpdateAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateAuthorActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(df.getValueAt(selectIndex,0).toString());
        
        
        String name,phn,adrs;
        name = jtxtfldNameAuthor.getText();
        phn = jtxtfldPhoneAuthor.getText();
        adrs = jTextArea1.getText();
        
        try{
                update = con1.prepareStatement("update author_table set name=?,phone=?,address=? where id=?");
                update.setString(1, name);
                update.setString(2, phn);
                update.setString(3, adrs);
                update.setInt(4, id);
                int k = update.executeUpdate();
                
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data Updated!");
                    
                    jtxtfldNameAuthor.setText("");
                    jtxtfldPhoneAuthor.setText("");
                    jTextArea1.setText("");
                    jtxtfldNameAuthor.requestFocus();
                    
                    table_author();
                    jButtonAddAuthor.setEnabled(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonUpdateAuthorActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        //int id = Integer.parseInt(df.getValueAt(selectIndex,0).toString());
        jtxtfldNameAuthor.setText(df.getValueAt(selectIndex,1).toString());
        jtxtfldPhoneAuthor.setText(df.getValueAt(selectIndex,2).toString());
        jTextArea1.setText(df.getValueAt(selectIndex,3).toString());
        
        jButtonAddAuthor.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Author().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton jButtonAddAuthor;
    private javax.swing.JToggleButton jButtonDeleteAuthor;
    private javax.swing.JToggleButton jButtonUpdateAuthor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jtxtfldNameAuthor;
    private javax.swing.JTextField jtxtfldPhoneAuthor;
    // End of variables declaration//GEN-END:variables
}
