
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    Connection con1,con2,con3;
    PreparedStatement select,insert,add,delete,update,tbl,pst;
    ResultSet rs;
    public Books() {
        Connect();
        initComponents();
        table_book();
        Category();
        Author();
        Publisher();
    }
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUP.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
            } catch (SQLException ex) {
                System.out.print(ex);
            }
    }
    private void table_book()
    {
        try{
            tbl = con1.prepareStatement("select * from book_table");
            rs = tbl.executeQuery();
            
            javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable4.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String cat = rs.getString("category");
                String auth = rs.getString("author");
                String pub = rs.getString("publisher");
                String pageno = rs.getString("page_no");
                
                String row[] = {id,name,cat,auth,pub,pageno};
                df.addRow(row);
            }
        }catch(SQLException ex)
        {
            System.out.print(ex);
    }
    }
    public void Category() {
		try {
			pst = con1.prepareStatement("SELECT * FROM category_table");
			rs = pst.executeQuery();
			jComboBoxBookCategory.removeAllItems();
			while (rs.next()) {
				String bookName = rs.getString("category");
				jComboBoxBookCategory.addItem(bookName);
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
    }
    public void Author() {
		try {
			pst = con1.prepareStatement("SELECT * FROM author_table");
			rs = pst.executeQuery();
			jComboBoxBookAuthor.removeAllItems();
			while (rs.next()) {
				String autname = rs.getString("Name");
				jComboBoxBookAuthor.addItem(autname);
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
    }
    public void Publisher() {
		try {
			pst = con1.prepareStatement("SELECT * FROM publisher_table");
			rs = pst.executeQuery();
			jComboBoxBookPublisher.removeAllItems();
			while (rs.next()) {
				String pbname = rs.getString("Name");
				jComboBoxBookPublisher.addItem(pbname);
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtfldBookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtfldPagenmbr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxBookPublisher = new javax.swing.JComboBox();
        jComboBoxBookCategory = new javax.swing.JComboBox();
        jComboBoxBookAuthor = new javax.swing.JComboBox<>();
        jButtonDeleteBook = new javax.swing.JToggleButton();
        jButtonAddBook = new javax.swing.JToggleButton();
        Back = new javax.swing.JToggleButton();
        jButtonUpdateBook1 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book Name", "Category", "Author", "Publisher", "No. of Pages"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 550, 650));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Publisher");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 30));
        getContentPane().add(jtxtfldBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 310, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Pages");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 30));
        getContentPane().add(jtxtfldPagenmbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 310, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Book Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Author");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 30));

        jComboBoxBookPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBookPublisherActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBookPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 300, 30));

        jComboBoxBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBookCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBookCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 300, 30));

        getContentPane().add(jComboBoxBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 300, 30));

        jButtonDeleteBook.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDeleteBook.setText("Delete");
        jButtonDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 90, 40));

        jButtonAddBook.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddBook.setText("Add");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 40));

        Back.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 200, 40));

        jButtonUpdateBook1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonUpdateBook1.setText("Edit");
        getContentPane().add(jButtonUpdateBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 90, 40));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\Smaller\\Book.jpg")); // NOI18N
        jToggleButton1.setText("Book");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Library.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBookPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBookPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBookPublisherActionPerformed

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        // TODO add your handling code here:
        String name,cat,pub,auth,pageno;
        
        name = jtxtfldBookName.getText();
        cat = (String) jComboBoxBookCategory.getSelectedItem();
        auth = (String) jComboBoxBookAuthor.getSelectedItem();
        pub = (String) jComboBoxBookPublisher.getSelectedItem();
        pageno = (String) jtxtfldPagenmbr.getText();        
        
        
        try{
            if(name.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please fill up the text field to add new book!");
            }
            else
            {
                insert = con1.prepareStatement("insert into book_table(Name,Category,Author,Publisher,Page_no) values(?,?,?,?,?)");
                insert.setString(1, name);
                insert.setString(2, cat);
                insert.setString(3, auth);
                insert.setString(4, pub);
                insert.setString(5, pageno);
                int k = insert.executeUpdate();
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data inserted!");
                    
                    jtxtfldBookName.setText("");
                    jComboBoxBookCategory.setSelectedIndex(0);
                    jComboBoxBookAuthor.setSelectedIndex(0);
                    jComboBoxBookPublisher.setSelectedIndex(0);
                    jtxtfldPagenmbr.setText("");
                    jtxtfldBookName.requestFocus();
                   
                    table_book();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jComboBoxBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBookCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBookCategoryActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LibrarianMenu back = new LibrarianMenu();
        back.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButtonDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Back;
    private javax.swing.JToggleButton jButtonAddBook;
    private javax.swing.JToggleButton jButtonDeleteBook;
    private javax.swing.JToggleButton jButtonUpdateBook1;
    private javax.swing.JComboBox<String> jComboBoxBookAuthor;
    private javax.swing.JComboBox jComboBoxBookCategory;
    private javax.swing.JComboBox jComboBoxBookPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jtxtfldBookName;
    private javax.swing.JTextField jtxtfldPagenmbr;
    // End of variables declaration//GEN-END:variables

}