
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    Connection con1,con2,con3;
    PreparedStatement select,insert,add,delete,update,tbl,pst;
    ResultSet rs;
    public IssueBook() {
        Connect();
        initComponents();
        issue_table();
        Book();
    }
    
public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUP.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
            } catch (SQLException ex) {
                System.out.print(ex);
            }
    }
public void Book() {
		try {
			pst = con1.prepareStatement("SELECT * FROM book_table");
			rs = pst.executeQuery();
			jComboBoxBook.removeAllItems();
			while (rs.next()) {
				String bookName = rs.getString("Name");
				jComboBoxBook.addItem(bookName);
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
    }
public void issue_table(){
    try{
            tbl = con1.prepareStatement("select * from issue_table");
            rs = tbl.executeQuery();
            
            javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("member_id");
                String book = rs.getString("books");
                String idate = rs.getString("issue_date");
                String rdate = rs.getString("return_date");
                
                String row[] = {name,book,idate,rdate};
                df.addRow(row);
            }
        }catch(SQLException ex)
        {
            System.out.print(ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldMID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxBook = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jReturnDate = new com.toedter.calendar.JDateChooser();
        jIssueDate = new com.toedter.calendar.JDateChooser();
        Back = new javax.swing.JToggleButton();
        IssueBook = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Return Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 50));
        getContentPane().add(jTextFieldMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 280, 50));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Member Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 50));

        jComboBoxBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBookActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 280, 50));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("Books");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 50));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("Issue Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 50));
        getContentPane().add(jReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 280, 50));
        getContentPane().add(jIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 280, 50));

        Back.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Back.setText("Cancel");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 140, 50));

        IssueBook.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        IssueBook.setText("Issue Book");
        IssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookActionPerformed(evt);
            }
        });
        getContentPane().add(IssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 140, 50));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\IssueBook.jpg")); // NOI18N
        jToggleButton1.setText("Issue Book");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 240, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Books", "Issue Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 490, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookActionPerformed
        // TODO add your handling code here:
        String mid,books;
        
        mid = (String) jTextFieldMID.getText();
        books = (String) jComboBoxBook.getSelectedItem();
        
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String DateFormat = date_format.format(jIssueDate.getDate());
        
        SimpleDateFormat date_format1 = new SimpleDateFormat("yyyy-MM-dd");
        String DateFormat1 = date_format.format(jReturnDate.getDate());
        
        try{
            if(mid.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please fill up the text field to add new book!");
            }
            else
            {
                insert = con1.prepareStatement("insert into issue_table(member_id,books,issue_date,return_date) values(?,?,?,?)");
                insert.setString(1, mid);
                insert.setString(2, books);
                insert.setString(3, DateFormat);
                insert.setString(4, DateFormat1);
                
                int k = insert.executeUpdate();
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data inserted!");
                    issue_table();
                    jTextFieldMID.setText("");
                    jComboBoxBook.setSelectedIndex(0);
                    jTextFieldMID.requestFocus();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_IssueBookActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LibrarianMenu back = new LibrarianMenu();
        back.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jComboBoxBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Back;
    private javax.swing.JToggleButton IssueBook;
    private javax.swing.JComboBox<String> jComboBoxBook;
    private com.toedter.calendar.JDateChooser jIssueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser jReturnDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMID;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
