
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con1,con2,con3;
    PreparedStatement select;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        SLogin = new javax.swing.JToggleButton();
        ALogin = new javax.swing.JToggleButton();
        TLogin = new javax.swing.JToggleButton();
        SignUp = new javax.swing.JToggleButton();
        pwrd = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton4.setText("jToggleButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 154, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 219, -1, -1));

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 154, 196, 30));

        SLogin.setText("Login as Student");
        SLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLoginActionPerformed(evt);
            }
        });
        getContentPane().add(SLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 125, 45));

        ALogin.setText("Login as Admin");
        ALogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALoginActionPerformed(evt);
            }
        });
        getContentPane().add(ALogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 125, 45));

        TLogin.setText("Login as Teacher");
        TLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 125, 45));

        SignUp.setText("Sign UP");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        pwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwrdActionPerformed(evt);
            }
        });
        getContentPane().add(pwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 200, 30));

        jToggleButton1.setText("Exit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w7n7rb (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, 1080, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void TLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLoginActionPerformed
          String username,password,usernamedb,passworddb;
        try{
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
                            
                username = uname.getText();
                password = new String(pwrd.getPassword());
                select = con1.prepareStatement("select * From teacher_info");
                ResultSet rs = select.executeQuery();
                
                while(rs.next())
                {
                usernamedb = rs.getString("username");
                passworddb = rs.getString("pass_word");
                if(username.equals(usernamedb) && password.equals(passworddb))
                {
                JOptionPane.showMessageDialog(this, "Enterd!");
                this.dispose();
                new MemberMenu().setVisible(true);
                break;
                }
                if(rs.isLast())
                {
                JOptionPane.showMessageDialog(this,"Wrong id or password...");
                }
                }
                }catch (SQLException ex){
                System.out.print(ex);
                }        // TODO add your handling code here:
    }//GEN-LAST:event_TLoginActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
       
        this.dispose();
        SignUP signup = new SignUP();
        signup.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    private void pwrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwrdActionPerformed

    private void SLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLoginActionPerformed

        String username,password,usernamedb,passworddb;
        try{
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
                
                username = uname.getText();
                password = new String(pwrd.getPassword());
                select = con1.prepareStatement("select * From student_info");
                ResultSet rs = select.executeQuery();
                
                System.out.print(username+ "\n" +password);
                while(rs.next())
                {
                usernamedb = rs.getString("username");
                passworddb = rs.getString("pass_word");
                
                System.out.print(usernamedb+ "\n" +passworddb);
                
                if(username.equals(usernamedb) && password.equals(passworddb))
                {
                JOptionPane.showMessageDialog(this, "Enterd!");
                this.dispose();
                new MemberMenu().setVisible(true);
                break;
                }
                if(rs.isLast())
                {
                JOptionPane.showMessageDialog(this,"Wrong id or password...");
                }
                }
                }catch (SQLException ex){
                System.out.print(ex);
                }        // TODO add your handling code here:
    }//GEN-LAST:event_SLoginActionPerformed

    private void ALoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALoginActionPerformed
        // TODO add your handling code here:
        String username,password,usernamedb,passworddb;
        try{
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
                
                username = uname.getText();
                password = new String(pwrd.getPassword());
                select = con1.prepareStatement("select * From admin");
                ResultSet rs = select.executeQuery();
                
                System.out.print(username+ "\n" +password);
                while(rs.next())
                {
                usernamedb = rs.getString("username");
                passworddb = rs.getString("pass_word");
                
                System.out.print(usernamedb+ "\n" +passworddb);
                
                if(username.equals(usernamedb) && password.equals(passworddb))
                {
                JOptionPane.showMessageDialog(this, "Enterd!");
                this.dispose();
                new LibrarianMenu().setVisible(true);
                break;
                }
                if(rs.isLast())
                {
                JOptionPane.showMessageDialog(this,"Wrong id or password...");
                }
                }
                }catch (SQLException ex){
                System.out.print(ex);
                }
    }//GEN-LAST:event_ALoginActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ALogin;
    private javax.swing.JToggleButton SLogin;
    private javax.swing.JToggleButton SignUp;
    private javax.swing.JToggleButton TLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPasswordField pwrd;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
