/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class MemberMenu extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianMenu
     */
    public MemberMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Books = new javax.swing.JToggleButton();
        SearchBook = new javax.swing.JToggleButton();
        ReqBook = new javax.swing.JToggleButton();
        LogOut = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Books.setBackground(new java.awt.Color(255, 255, 255));
        Books.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        Books.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\Book.jpg")); // NOI18N
        Books.setText("Books");
        Books.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Books.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksActionPerformed(evt);
            }
        });
        getContentPane().add(Books, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 300, 110));

        SearchBook.setBackground(new java.awt.Color(255, 255, 255));
        SearchBook.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        SearchBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\SearchBook.jpg")); // NOI18N
        SearchBook.setText("Search Book");
        SearchBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SearchBook.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBookActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 300, 110));

        ReqBook.setBackground(new java.awt.Color(255, 255, 255));
        ReqBook.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        ReqBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\Category.jpg")); // NOI18N
        ReqBook.setText("Req Book");
        ReqBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReqBook.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ReqBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqBookActionPerformed(evt);
            }
        });
        getContentPane().add(ReqBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 300, 110));

        LogOut.setBackground(new java.awt.Color(255, 255, 255));
        LogOut.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksActionPerformed
        // TODO add your handling code here:
        this.dispose();
    MemBook mbook = new MemBook();
    mbook.setVisible(true); 
    }//GEN-LAST:event_BooksActionPerformed

    private void SearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBookActionPerformed

    private void ReqBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqBookActionPerformed
        // TODO add your handling code here:
        this.dispose();
    ReqBook rbook = new ReqBook();
    rbook.setVisible(true); 
    }//GEN-LAST:event_ReqBookActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    Login login = new Login();
    login.setVisible(true); 
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MemberMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Books;
    private javax.swing.JToggleButton LogOut;
    private javax.swing.JToggleButton ReqBook;
    private javax.swing.JToggleButton SearchBook;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
