
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    Connection con1,con2,con3;
    PreparedStatement select,insert,add,delete,update,tbl,pst;
    ResultSet rs;
    public ReturnBook() {
        Connect();
        initComponents();
        issue_table();
        Book();
    }
    
public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUP.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
            } catch (SQLException ex) {
                System.out.print(ex);
            }
    }
public void Book() {
		try {
			pst = con1.prepareStatement("SELECT * FROM book_table");
			rs = pst.executeQuery();
			jComboBoxBook1.removeAllItems();
			while (rs.next()) {
				String bookName = rs.getString("Name");
				jComboBoxBook1.addItem(bookName);
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
    }
public void issue_table(){
    try{
            tbl = con1.prepareStatement("select * from issue_table");
            rs = tbl.executeQuery();
            
            javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("member_id");
                String book = rs.getString("books");
                String idate = rs.getString("issue_date");
                String rdate = rs.getString("return_date");
                
                String row[] = {name,book,idate,rdate};
                df.addRow(row);
            }
        }catch(SQLException ex)
        {
            System.out.print(ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldMID1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxBook1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jReturnDate1 = new com.toedter.calendar.JDateChooser();
        Back = new javax.swing.JToggleButton();
        jButtonreturnadd1 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Return Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, 50));
        getContentPane().add(jTextFieldMID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 280, 50));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Member Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 50));

        getContentPane().add(jComboBoxBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 280, 50));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("Books");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 50));
        getContentPane().add(jReturnDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 280, 50));

        Back.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Back.setText("Cancel");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 140, 50));

        jButtonreturnadd1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonreturnadd1.setText("Return Book");
        jButtonreturnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreturnadd1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonreturnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 50));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\ReturnBook.jpg")); // NOI18N
        jToggleButton1.setText("Return Book");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Books", "Issue Book", "Return Book"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 150, 470, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonreturnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreturnadd1ActionPerformed
        // TODO add your handling code here:
        String mid,books;
        
        mid = (String) jTextFieldMID1.getText();
        books = (String) jComboBoxBook1.getSelectedItem();
        
        SimpleDateFormat date_format1 = new SimpleDateFormat("yyyy-MM-dd");
        String DateFormat1 = date_format1.format(jReturnDate1.getDate());
        
        try{
            if(mid.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please fill up the text field to add new book!");
            }
            else
            {
                insert = con1.prepareStatement("insert into issue_table(member_id,books,return_date) values(?,?,?)");
                insert.setString(1, mid);
                insert.setString(2, books);
                insert.setString(3, DateFormat1);
                
                int k = insert.executeUpdate();
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data inserted!");
                    
                    jTextFieldMID1.setText("");
                    jComboBoxBook1.setSelectedIndex(0);
                    jTextFieldMID1.requestFocus();
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonreturnadd1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LibrarianMenu back = new LibrarianMenu();
        back.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        //int id = Integer.parseInt(df.getValueAt(selectIndex,0).toString());
        jTextFieldMID1.setText(df.getValueAt(selectIndex,1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Back;
    private javax.swing.JToggleButton jButtonreturnadd1;
    private javax.swing.JComboBox<String> jComboBoxBook1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser jReturnDate1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMID1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
