
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IFTI
 */
public class TeacherList extends javax.swing.JFrame {

    /**
     * Creates new form StudentList
     */
    Connection con1,con2,con3;
    PreparedStatement select,insert,add,delete,update,tbl,pst;
    ResultSet rs;
    public TeacherList() {
        initComponents();
        Connect();
        tprofile_table();
        
    }
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUP.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
            } catch (SQLException ex) {
                System.out.print(ex);
            }
    }
    public void tprofile_table()
    {
        try{
            tbl = con1.prepareStatement("select * from teacher_profile");
            rs = tbl.executeQuery();
            
            javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable5.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                String id = rs.getString("uni_id");
                String name = rs.getString("username");
                String email = rs.getString("email");
                
                String row[] = {id,name,email};
                df.addRow(row);
            }
        }catch(SQLException ex)
        {
            System.out.print(ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtfldNameMember = new javax.swing.JTextField();
        jtxtfldPhoneMember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonDeleteMember = new javax.swing.JToggleButton();
        jButtonAddMember = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        jButtonUpdateMember = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Uni ID", "Username", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable5);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 0, 520, 650));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Uni ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 40));
        getContentPane().add(jtxtfldNameMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 280, 40));
        getContentPane().add(jtxtfldPhoneMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 280, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 40));
        getContentPane().add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 280, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, 40));

        jButtonDeleteMember.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonDeleteMember.setText("Delete");
        getContentPane().add(jButtonDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, 50));

        jButtonAddMember.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonAddMember.setText("Add");
        jButtonAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMemberActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 110, 50));

        back.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 190, 50));

        jButtonUpdateMember.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonUpdateMember.setText("Edit");
        jButtonUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateMemberActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 110, 50));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFTI\\Documents\\Icons\\Smaller\\Teacher.jpg")); // NOI18N
        jToggleButton1.setText("Teachers List");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMemberActionPerformed
        // TODO add your handling code here:
        String id,uname,email;
        id = jtxtfldNameMember.getText();
        uname = jtxtfldPhoneMember.getText();
        email = jTextArea3.getText();
        
        
        try{
            if(id.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please fill up the text field to add new member!");
            }
            else
            {
                insert = con1.prepareStatement("insert into teacher_profile(uni_id,username,email) values(?,?,?)");
                insert.setString(1, id);
                insert.setString(2, uname);
                insert.setString(3, email);
                int k = insert.executeUpdate();
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data inserted!");
                    tprofile_table();
                    
                    jtxtfldNameMember.setText("");
                    jtxtfldPhoneMember.setText("");
                    jTextArea3.setText("");
                    jtxtfldNameAuthor.requestFocus();
                   
                    tprofile_table();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonAddMemberActionPerformed

    private void jButtonUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateMemberActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable5.getModel();
        int selectIndex = jTable5.getSelectedRow();
        int id = Integer.parseInt(df.getValueAt(selectIndex,0).toString());
        
        
        String name,phn,adrs;
        name = jtxtfldNameMember.getText();
        phn = jtxtfldPhoneMember.getText();
        adrs = jTextArea3.getText();
        
        try{
                update = con1.prepareStatement("update teacher_profile set uni_id=?,username=?,email=? where id=?");
                update.setString(1, name);
                update.setString(2, phn);
                update.setString(3, adrs);
                update.setInt(4, id);
                int k = update.executeUpdate();
                
                if(k == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data Updated!");
                    
                    jtxtfldNameMember.setText("");
                    jtxtfldPhoneMember.setText("");
                    jTextArea3.setText("");
                    jtxtfldNameMember.requestFocus();
                    
                    tprofile_table();
                    jButtonAddMember.setEnabled(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error!");
                }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonUpdateMemberActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel df = (javax.swing.table.DefaultTableModel) jTable5.getModel();
        int selectIndex = jTable5.getSelectedRow();
        
        jtxtfldNameMember.setText(df.getValueAt(selectIndex,0).toString());
        jtxtfldPhoneMember.setText(df.getValueAt(selectIndex,1).toString());
        jTextArea3.setText(df.getValueAt(selectIndex,2).toString());
        
        jButtonAddMember.setEnabled(false);
    }//GEN-LAST:event_jTable5MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LibrarianMenu back = new LibrarianMenu();
        back.setVisible(true); 
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton jButtonAddMember;
    private javax.swing.JToggleButton jButtonDeleteMember;
    private javax.swing.JToggleButton jButtonUpdateMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextArea3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jtxtfldNameMember;
    private javax.swing.JTextField jtxtfldPhoneMember;
    // End of variables declaration//GEN-END:variables
}
